CREATE TABLE IF NOT EXISTS blogs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  titulo VARCHAR(150) NOT NULL,
  categoria VARCHAR(80) NOT NULL,
  resumo TEXT NOT NULL,
  foto_url TEXT,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
